package com.example.happybirthdayapp

import android.os.Bundle
import android.widget.Button
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.example.happybirthdayapp.models.Dice

class MainActivity : AppCompatActivity() {

    /**
     * function to update the textView by passing in the number generated
     */
    private fun updateRolledText(rolledNumber: Int) {
        val rollResultText: TextView = findViewById(R.id.Dice_Roll_Result)
        rollResultText.text = rolledNumber.toString()
    }

    /**
     *function to compare rolled number vs lucky number
     *@param rolledNumber random number generated by the dice class
     *@param luckyNumber random number that's generated by the main page
     */
    private fun checkLuckyNumber(rolledNumber: Int, luckyNumber: Int) {
        val resultToast: Toast = Toast.makeText(this, "", Toast.LENGTH_SHORT)
        when (rolledNumber) {
            luckyNumber -> resultToast.setText("Congrats!")
            else -> {
                resultToast.setText("Unlucky")
            }
        }
        resultToast.show()
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        //gets the button and assigns it the variable rollButton
        //still have to do it by the ID assigned in the design window, just happens that its also connected to a int that AS handles.
        val rollButton: Button = findViewById(R.id.Roll_Dice_Button)
        //this serves as a function but without the ()
        rollButton.setOnClickListener {
            val dice = Dice(20)
            val diceRange: IntRange = 1..20
            val diceNumber: Int = dice.rollDice()
            val aiNumber: Int = diceRange.random()
            checkLuckyNumber(diceNumber, aiNumber)
            updateRolledText(diceNumber)

        }


    }
}